---
title: "R packaging"
author: "Emy Guilbault and Arthur Rodrigues"
date: "2023-09-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Summary (Emy)

Here are some questions to ask yourself when you are interested in coding and/or using functions:

*Why?* what do you need? -> If you need to tailor some existing functions, if you are going to use them many times.

*Who* is it for? -> Are the changes or the created function of any use for other coders or anyone working in similar field?

*Where*? -> do you need a place to share code and make it available. github is an option. CRAN make it more accessible.

*How*?-> We are going to dig into the steps of creating a package!


### Presentation: Motivation and use (ARTHUR)


One of the main principles in good coding practice is 'do not repeat yourself'. There are some options to achieve these goal. One of them is to create a loop, when your task is only to repeat a procedure with different input. Other option is to create a custom function, which allow you to modify predefined places of your code using arguments. 

When we are creating a analysis or cleaning data it could be useful to write a function and let it in a separated file. Then, you only need to add a `source()` in your script to load your custom function in the R environment and you are able use it across your script. Using this approach will make your code more readable and tidy, because instead of several lines of code to do a step of your analysis, you now have only few lines of code using your custom function. Moreover, you can use it several times in your script without need to copy and paste your code and change few characters. 

Therefore, for a project you are working, you can create as much functions you need, and load it your scripts using the `source()` function. However, if you have created a set of functions that could be useful in other projects or for other people, it could be nice to create an R package. Which could also let your coding more susceptible to errors. 




### Pros and cons to create a package
Since you have some custom functions, you might wonder if it is a good idea to create a package. 

Pros:   
- Easy access to functions that you've created (it is easier to add a `library()` call in your script than a `source()`)  
- Your functions have help pages
- Your functions could be used by others
- Users could give feedback to your function 

Cons:  
- Could be time consuming to create and maintain a package
- Users could give feedback to your functions (bugs)



 
### How to create a package:  

 
#### Package components (Rfiles, metadata and dependencies)  (Emy)
DESCRIPTION file
R/ directory for R files that contain your functions
NAMESPACE file (you don’t need to manually create this)

 
#### Documentation (Emy)


#### Maintenance and release + CRAN checking  

#### Testing  


#### Summary of resources